### ISSUE TITLE
Problem $1 & $2

### ISSUE THREAD

**Issue by PiekarskiKarol** [flcdrg/replace-multiple-action#271]
Hi!

I have a problem with $1 and $2 when replacing a string.

Do you need this in the `replace-multiple-action/src/replaceInstances.ts` file?

content = content.replace(new RegExp(pattern, 'g'), `$1${pair.replace}$2`);

Why is this a problem? 

I am doing an auto-deploy for my private plugin. With your action I need to replace the plugin version and path.
Now I have `[VERSION]` and after replacing `$1v0.1.0$2`.

Maybe there is a hack to just have `v0.1.0`?

BR
Charles

**Comment by flcdrg** [comment]
I've allowed the build to run on your PR - it is failing because the output has changed.

**Comment by carefreepineapple** [comment]
I'm having the same problem.

expecting:
```## blahupdated```
getting:
```## $1blahupdated$2```

I tried specifying an empty prefix and suffix, no change.
```
    - name: injecting secrets
      uses: flcdrg/replace-multiple-action@v1
      with:
        files: '${{ github.workspace }}/*.ps1'
        find: '[{ "find": "$SCRIPT_SECRET", "replace": "${{ secrets.SCRIPT_SECRET }}" }]'
        prefix: ''
        suffix: ''
```

any suggestions?

maybe wrapping `content = content.replace(new RegExp(pattern, 'g'), $1${pair.replace}$2);` in a conditional and only adding $1 (prefix) and $2 (suffix) when they are not null?
