### ISSUE TITLE
wildcard for foldername

### ISSUE THREAD

**Issue by carefreepineapple** [flcdrg/replace-multiple-action#473]
## Request
In usage it appears that the wildcard can only match filenames, can you expand that functionality to include folder names? heck, can you make it so that the `files:` input accepts regex?
ie.
```
- uses: flcdrg/replace-multiple-action@latest
        with:
            files: '${{ github.workspace }}/nodejs-*/.env'
            find: '[{ "find": "DB_HOST=", "replace": "DB_HOST=${{ vars.MARIADB_HOST }}" }]'
            prefix: '^'
            suffix: '.*'
```
## Current Behavior
```
Run flcdrg/replace-multiple-action@latest
starting
Updating /home/runner/work/serverlist/serverlist/nodejs-dbschema/.env
```
## Requested Behavior
```
Run flcdrg/replace-multiple-action@latest
starting
Updating /home/runner/work/serverlist/serverlist/nodejs-dbschema/.env
Updating /home/runner/work/serverlist/serverlist/nodejs-scraper/.env
```
