### ISSUE TITLE
still getting $1 and $2 injected in replacement

### ISSUE THREAD

**Issue by carefreepineapple** [flcdrg/replace-multiple-action#474]
## Issue:
Similar to the previous issue: https://github.com/flcdrg/replace-multiple-action/issues/271
I'm still seeing `$1` and `$2` injected around the replacement string.  It looks like this is only happening for the first match, but I believe this may be because its failing to match and replace the rest of the items in the json array.

## Reproduction:
I'm using:
```
- uses: flcdrg/replace-multiple-action@latest
        with:
            files: '${{ github.workspace }}/nodejs-*/.env'
            find: '[{ "find": "DB_HOST=", "replace": "DB_HOST=${{ vars.MARIADB_HOST }}"}, { "find": "DB_USER=", "replace": "${{ vars.MARIADB_USER }}" }, { "find": "DB_PASS=", "replace": "${{ secrets.MARIADBPASS }}" }, { "find": "DB_NAME=", "replace": "${{ vars.DB_NAME }}" }]'
            prefix: '^'
            suffix: '.*'
```
The file contents then looks like:
```
~$ sudo cat .env
$1DB_HOST=localhost$2
DB_USER=dbuser
DB_PASS=dbpass
DB_NAME=dbname
```
